[package]
name = "icepaper"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/pop-os/iced.git", features = ["image", "debug", "wayland", "winit", "wgpu", "tokio" ] }
rfd = "0.15.2"
